### PR TITLE
fix docs

### PR DESCRIPTION
**Pull request by strengejacke**
# Description

This PR aims at adding this feature...

# Proposed Changes

I changed the `foo` function so that ...

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
well that's a lot of fails 😞

**Comment by DominiqueMakowski** [comment]
GH-CI is a bit more digest and says:

```
Quitting from lines 677-680 (bayes_factors.Rmd) 
##[error]Error: processing vignette 'bayes_factors.Rmd' failed with diagnostics:
Unable to reconstruct prior estimates.
Perhaps the emmGrid object has been transformed? See function details.
```

**Comment by strengejacke** [comment]
Seems to be related to: 

> Quitting from lines 677-680 (bayes_factors.Rmd)

**Comment by mattansb** [comment]
Will take a look... I thought I just fixed that :/

**Comment by mattansb** [comment]
This work for once updating `modelbased` to dev.

**Comment by DominiqueMakowski** [comment]
😁 

```
❯ checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'distribution'
    ‘xi’ ‘mu’ ‘phi’ ‘power’
```
```
> test_check("bayestestR")
── 1. Failure: emmGrid bayesfactor_restricted (@test-emmGrid.R#97)  ────────────
xrbf$Prior_prob not equal to c(0.49775, 0.504).
1/2 mismatches
[1] 0.488 - 0.498 == -0.01


── 2. Failure: si.rstanarm (@test-si.R#39)  ────────────────────────────────────
res$CI_low not equal to c(-0.013, 0.452).
2/2 mismatches (average diff: 0.0962)
[1] 0.0766 - -0.013 ==  0.0896
[2] 0.3492 -  0.452 == -0.1028


── 3. Failure: si.rstanarm (@test-si.R#40)  ────────────────────────────────────
res$CI_high not equal to c(3.168, 1.818).
1/2 mismatches
[1] 3.07 - 3.17 == -0.101


══ testthat results  ═══════════════════════════════════════════════════════════
[ OK: 204 | SKIPPED: 2 | WARNINGS: 5 | FAILED: 3 ]
1. Failure: emmGrid bayesfactor_restricted (@test-emmGrid.R#97) 
2. Failure: si.rstanarm (@test-si.R#39) 
3. Failure: si.rstanarm (@test-si.R#40) 
```

**Comment by mattansb** [comment]
For some reason random sampling (such as used by stan's MCMC) is somehow random across different systems.... Nothing to do (there is no `skip_on_hg`?)

**Comment by DominiqueMakowski** [comment]
but diffs seems to be pretty narrow, maybe we could increase the tolerance so that it's resistant to small variability?

**Comment by mattansb** [comment]
But I want to know if the output changes after some change I've made to the code, so I don't really care if it consistently fails on some system - for that I need a high(ish) tolerance :/

Maybe `skip_on_ci` will work?

**Comment by mattansb** [comment]
`skip_on_ci` Should work https://github.com/r-lib/testthat/issues/970

I'll try in on `effectsize`, where I'm getting a similar error.

**Comment by mattansb** [comment]
Yup - worked on effectsize.
Adding this here....

**Comment by mattansb** [comment]
Why are there so many Ubuntu checks and only 1 Windows check? 🤔

**Pull request merged**
