### PR TITLE
diagnostic_draws

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
``` r
library(brms)
library(dplyr)
library(ggplot2)
library(patchwork)

set.seed(333)

model <- brms::brm(mpg ~ wt * vs * carb + s(hp) + (1 + wt * vs * carb | cyl), 
                   data = mtcars, iter = 400, refresh = 0, 
                   control = list(adapt_delta = 0.50, max_treedepth = 7))
#> Compiling Stan program...
#> Start sampling
#> Warning: There were 225 divergent transitions after warmup. See
#> http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup
#> to find out why this is a problem and how to eliminate them.
#> Warning: There were 557 transitions after warmup that exceeded the maximum treedepth. Increase max_treedepth above 7. See
#> http://mc-stan.org/misc/warnings.html#maximum-treedepth-exceeded
#> Warning: Examine the pairs() plot to diagnose sampling problems
#> Warning: The largest R-hat is 1.79, indicating chains have not mixed.
#> Running the chains for more iterations may help. See
#> http://mc-stan.org/misc/warnings.html#r-hat
#> Warning: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.
#> Running the chains for more iterations may help. See
#> http://mc-stan.org/misc/warnings.html#bulk-ess
#> Warning: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable.
#> Running the chains for more iterations may help. See
#> http://mc-stan.org/misc/warnings.html#tail-ess

diag <- bayestestR::diagnostic_draws(model)

table(diag$Divergent)
#> 
#>   0   1 
#> 575 225
table(diag$Tree_Depth)
#> 
#>   1   2   3   4   5   6   7 
#>   9 116  38  19  25  36 557


diag$iter_group <- row.names(diag)
data <- cbind(mtcars, insight::get_predicted(model)) %>% 
  bayestestR::reshape_iterations() %>% 
  merge(diag, by = "iter_group") 

ggplot(data, aes(x = mpg, y = iter_value, color = as.factor(Divergent), group = iter_group)) +
  geom_line(alpha=0.3) + 
  geom_abline() 
```

``` r
ggplot(data, aes(x = mpg, y = iter_value, color = Tree_Depth, group = iter_group)) +
  geom_line(alpha=0.3) + 
  geom_abline() 
```

``` r
ggplot(data, aes(x = mpg, y = iter_value, color = n_Leapfrog, group = iter_group)) +
  geom_line(alpha=0.3) +
  geom_abline() 
```

``` r
ggplot(data, aes(x = mpg, y = iter_value, color = LogPosterior, group = iter_group)) +
  geom_line(alpha=0.3) +
  geom_abline() 
```

``` r
ggplot(data, aes(x = mpg, y = iter_value, color = Acceptance_Rate , group = iter_group)) +
  geom_line(alpha=0.3) +
  geom_abline() 
```

``` r
ggplot(data, aes(x = mpg, y = iter_value, color = Step_Size, group = iter_group)) +
  geom_line(alpha=0.3) +
  geom_abline() 
```

``` r
ggplot(data, aes(x = mpg, y = iter_value, color = Energy, group = iter_group)) +
  geom_line(alpha=0.3) +
  geom_abline() 
```

<sup>Created on 2021-05-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Don't mind the plots too much they are mostly for me because in my case I have a model and a group of predictions is completely off, and I'm trying to see if I can identify them with these diagnostic metrics

**Comment by mattansb** [comment]
@DominiqueMakowski What am I reviewing? I have no idea what I'm looking at 😅

**Comment by DominiqueMakowski** [comment]
haha don't mind the plots, just check whether the function ^^ currently we don't have any functions to gather convergence/algorithm quality information for each draws, which this function is a first draft at doing :)

**Comment by mattansb** [comment]
Sorry mate, I have no idea what any of this is 🙃
I guess I am not a *true* Bayesian after all.... *\<returns lightsaber>*

**Pull request merged**
