### PR TITLE
add warning for inaccurate BF/SI

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
> @IndrajeetPatil Having the paths as they are won't let the vignettes build (see tests).

This is such odd behavior. If you knit the vignette, works without any issues. If you run R CMD Check, it doesn't. You can merge as is and I can have a look at it then. Worse case scenario, we revert to remote URL for CRAN submission.

> Also, why are warnings in the vignette converted to errors???

I think failure to build a vignette is an error, and not a warning? Not sure.

**Comment by mattansb** [comment]
***DO NOT MERGE THIS YET***

**Comment by mattansb** [comment]
Thanks, but this was technically waiting for #473...

**Comment by IndrajeetPatil** [comment]
Oops, _ma culpa_ 🙊

**Pull request merged**
