### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by strengejacke** [comment]
merge

**Comment by strengejacke** [comment]
I'll add these two images in my signature whenever we both talk here on GitHub.

**Comment by DominiqueMakowski** [comment]
Yes master, just give me 5' until the last commit passes on travis... 😬

**Comment by DominiqueMakowski** [comment]
We must bring balance to the branches... Fear, anger and impatience lead to the master side. Peace, acceptance, and resilience are the pillars of the dev side

**Comment by strengejacke** [comment]
and a last one, though not (yet) from star wars:

its-kind-of-a-big-pull-request

**Comment by mattansb** [comment]
I love all of these!!!!

**Pull request merged**
