### PR TITLE
New unupdate function

### PR DESCRIPTION
**Pull request by strengejacke**

### CODE REVIEW

**Comment by mattansb** [comment]
Are you pulling the back-to-dev back to master?? 🤣🤣

**Comment by mattansb** [comment]
Can someone run this code and tell me if it works? I can't get `brms` to run on my computer...

```R
library(brms)
brms_mixed_6 <- insight::download_model("brms_mixed_6")

set.seed(222)
brms_mixed_6_p <- unupdate(brms_mixed_6)
bfsd1 <- bayesfactor_parameters(brms_mixed_6, brms_mixed_6_p, effects = "fixed")

set.seed(222)
bfsd2 <- bayesfactor_parameters(brms_mixed_6, effects = "fixed")

testthat::expect_equal(log(bfsd1$BF), log(bfsd2$BF), tolerance = .01)
```

**Comment by strengejacke** [comment]
```r
> brms_mixed_6 <- insight::download_model("brms_mixed_6")
> set.seed(222)
> brms_mixed_6_p <- unupdate(brms_mixed_6)
Sampling priors, please wait...
 Error in unupdate.brmsfit(brms_mixed_6) : 
  Error in sink(type = "output") : invalid connection 
3.
stop(model_prior) at unupdate.R#90
2.
unupdate.brmsfit(brms_mixed_6) at unupdate.R#18
1.
unupdate(brms_mixed_6) 
> bfsd1 <- bayesfactor_parameters(brms_mixed_6, brms_mixed_6_p, effects = "fixed")
 Error in .clean_priors_and_posteriors.brmsfit(posterior, prior, verbose = verbose,  : 
  object 'brms_mixed_6_p' not found 
4.
.clean_priors_and_posteriors.brmsfit(posterior, prior, verbose = verbose, 
    effects = effects, component = component, parameters = parameters) at utils_bayesfactor.R#7
3.
.clean_priors_and_posteriors(posterior, prior, verbose = verbose, 
    effects = effects, component = component, parameters = parameters) at bayesfactor_parameters.R#227
2.
bayesfactor_parameters.brmsfit(brms_mixed_6, brms_mixed_6_p, 
    effects = "fixed") at bayesfactor_parameters.R#132
1.
bayesfactor_parameters(brms_mixed_6, brms_mixed_6_p, effects = "fixed") 
```

**Comment by mattansb** [comment]
How about this?

```R
library(brms)
fit <- brm(extra ~ group + (1|ID), sleep,
           prior = set_prior("normal(0, 2)", class = "b"),
           chains = 1, iter = 1000, refresh = 0)


fit_p1 <- unupdate(fit) 

fit_p2 <- update(fit, sample_prior = "only", refresh = 0)

**Comment by strengejacke** [comment]
Since I'm back from vacation I can't run brms anymore. Not sure why? No error message, takes some time, but no object created.

**Comment by mattansb** [comment]
Huh... same here: https://github.com/paul-buerkner/brms/issues/965

**Comment by strengejacke** [comment]
ok, reverting back to rstan 2.19.3 seems to be the best solution for now...

**Comment by mattansb** [comment]
This also seems to help: https://discourse.mc-stan.org/t/rstan-on-windows/16673

Anyway, the new `unupdate()` function seems to work now for `brms`. Merging!

**Comment by mattansb** [comment]
(CI is still failing for any `brms` test... 🤷‍♂️)

**Comment by strengejacke** [comment]
> (CI is still failing for any `brms` test... 🤷‍♂️)

Have you checked locally? All brms-tests now should fail, because the check downloads official packages from CRAN, which don't have the above mentioned fix.

> This also seems to help: https://discourse.mc-stan.org/t/rstan-on-windows/16673

That works perfect w/o reverting to 2.19.x

**Comment by mattansb** [comment]
Yes, locally everything seems to work after that fix (:

**Pull request merged**
