### PR TITLE
draft mediation function

### PR DESCRIPTION
**Pull request by strengejacke**
re-implementation of https://strengejacke.github.io/sjstats/reference/mediation.html
I think it makes more sense in bayestestR.

### CODE REVIEW

**Comment by mattansb** [comment]
@strengejacke out if curiosity, can you share an example use for this?

**Comment by strengejacke** [comment]
[mediation.pdf](https://github.com/easystats/bayestestR/files/4830405/mediation.pdf)

**Comment by mattansb** [comment]
Ohhhh that's pretty cool!

**Comment by strengejacke** [comment]
@DominiqueMakowski I think this is ready to merge, you may take a look at it.

``` r
library(bayestestR)
library(mediation)
library(brms)
# load sample data
data(jobs)
set.seed(123)

# linear models, for mediation analysis
b1 <- lm(job_seek ~ treat + econ_hard + sex + age, data = jobs)
b2 <- lm(depress2 ~ treat + job_seek + econ_hard + sex + age, data = jobs)
# mediation analysis, for comparison with brms
m1 <- mediate(b1, b2, sims = 1000, treat = "treat", mediator = "job_seek")

# Fit Bayesian mediation model
f1 <- bf(job_seek ~ treat + econ_hard + sex + age)
f2 <- bf(depress2 ~ treat + job_seek + econ_hard + sex + age)
m2 <- brm(f1 + f2 + set_rescor(FALSE), data = jobs, cores = 4, refresh = 0)
#> Compiling the C++ model
#> Start sampling

mediation(m2)
#> # Causal Mediation Analysis for Stan Model
#> 
#>   Treatment: treat
#>   Mediator : job_seek
#>   Response : depress2
#> 
#> Effect                 | Estimate |          89% HDI
#> ----------------------------------------------------
#> Direct Effect (ADE)    |   -0.041 | [-0.107,  0.028]
#> Indirect Effect (ACME) |   -0.016 | [-0.036,  0.004]
#> Mediator Effect        |   -0.241 | [-0.288, -0.197]
#> Total Effect           |   -0.056 | [-0.131,  0.009]
#> 
#> Proportion mediated: 28.02% [-67.53%, 123.56%]

summary(m1)
#> 
#> Causal Mediation Analysis 
#> 
#> Quasi-Bayesian Confidence Intervals
#> 
#>                Estimate 95% CI Lower 95% CI Upper p-value
#> ACME            -0.0157      -0.0387         0.01    0.19
#> ADE             -0.0438      -0.1315         0.04    0.35
#> Total Effect    -0.0595      -0.1530         0.02    0.21
#> Prop. Mediated   0.2137      -2.0277         2.70    0.32
#> 
#> Sample Size Used: 899 
#> 
#> 
#> Simulations: 1000
mediation(m2, centrality = "mean", ci = .95)
#> # Causal Mediation Analysis for Stan Model
#> 
#>   Treatment: treat
#>   Mediator : job_seek
#>   Response : depress2
#> 
#> Effect                 | Estimate |          95% HDI
#> ----------------------------------------------------
#> Direct Effect (ADE)    |   -0.040 | [-0.123,  0.042]
#> Indirect Effect (ACME) |   -0.016 | [-0.041,  0.009]
#> Mediator Effect        |   -0.241 | [-0.294, -0.184]
#> Total Effect           |   -0.056 | [-0.138,  0.033]
#> 
#> Proportion mediated: 28.57% [-187.65%, 244.80%]
```

<sup>Created on 2020-06-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
cool, now also works for stanmvreg...

**Comment by strengejacke** [comment]
@DominiqueMakowski will you find time to review this the next days?

**Comment by strengejacke** [comment]
_bump_ (😺 )

**Pull request merged**
