### PR TITLE
Prepare CRAN release

### PR DESCRIPTION
**Pull request by strengejacke**
@DominiqueMakowski

Maybe you can submit this version to CRAN this week? Or are you unavailable the next days?

### CODE REVIEW

**Comment by strengejacke** [comment]
@DominiqueMakowski I would not change the package dependencies (i.e. versions) in the DESCRIPTION file - if you rely on the latest _datawizard_ (0.12.2), you get errors for Mac OS X. And I checked, _bayestestR_ is not affected by the API changes in _datawizard_, so it's OK to rely on 0.10.0

**Comment by DominiqueMakowski** [comment]
I can submit later today

**Comment by IndrajeetPatil** [comment]
We need to include `{cmdstanr}` in suggested deps (`Suggests`) since some tests require it.

**Comment by DominiqueMakowski** [comment]
https://win-builder.r-project.org/myBO6NPnnBYI/
https://win-builder.r-project.org/5v9TVgqc3RY2/
https://win-builder.r-project.org/iXroSK5i0vvD/

**Comment by strengejacke** [comment]
> https://win-builder.r-project.org/myBO6NPnnBYI/ https://win-builder.r-project.org/5v9TVgqc3RY2/ https://win-builder.r-project.org/iXroSK5i0vvD/

All win-builder checks are ok, nice!

**Comment by strengejacke** [comment]
@DominiqueMakowski have you already submitted? If not, we could probably address #627 first.

**Comment by DominiqueMakowski** [comment]
I'm holding out then

**Comment by strengejacke** [comment]
ok, PR is merged into this branch. Once the regular tests pass, you could submit (windows/ubuntu latest release and devel, mac os latest).

**Comment by strengejacke** [comment]
🟢

**Comment by strengejacke** [comment]
> 🟢

<sub>(@DominiqueMakowski: means, you can submit... 😬 )</sub>

**Comment by DominiqueMakowski** [comment]
submitted

**Comment by strengejacke** [comment]
Just saw, on CRAN! Yay!

**Pull request merged**
