### PR TITLE
ROPE range defaults to [-0.1,0.1] instead of '0 +/- .1 * sd(y)' for stan_glm in describe_posterior

### LINKED ISSUE #587: ROPE range defaults to [-0.1,0.1] instead of '0 +/- .1 * sd(y)' for stan_glm in describe_posterior
I believe this is a bug and apologise in advance if I am just not understanding the intended functionality correctly.

When:

model_bayes <- stan_glm(...)

It seems that 
describe_posterior(model_bayes) 

does not use rope_range = rope_range(model_bayes)
but instead a default rope_range = [-.1,.1] 

or at least I am only getting the `0 +/- .1 * sd(y)` rope_range for 

describe_posterior(model_bayes, rope_range = rope_range(model_bayes)) 

while 

describe_posterior(model_bayes, rope_range = 'default') 

always leads to ROPE [-0.10, 0.10]

Thanks for your help!

### PR DESCRIPTION
**Pull request by strengejacke**
Fixes #587

### CODE REVIEW

**Comment by strengejacke** [comment]
``` r
library(rstanarm)
d <- data.frame(
  y = c(
    7, 38, 6, 11, 0, 8, 6, 5, 28, 2, 32, 14,
    46, 19, 20, 28, 51, 12, 10, 1, 2, 22
  ),
  x = c(
    46, 41, 30, 30, 61, 42, 63, 13, 52, 59, 42, 45,
    55, 47, 36, 48, 70, 67, 50, 34, 72, 46
  )
)
m <- stan_glm(y ~ x, data = d)
bayestestR::describe_posterior(m)
#> Summary of Posterior Distribution
#> 
#> Parameter   | Median |          95% CI |     pd |          ROPE | % in ROPE |  Rhat |     ESS
#> ---------------------------------------------------------------------------------------------
#> (Intercept) |   9.00 | [-15.60, 33.02] | 77.55% | [-1.48, 1.48] |     7.29% | 1.000 | 3213.00
#> x           |   0.16 | [ -0.32,  0.66] | 76.02% | [-1.48, 1.48] |      100% | 1.000 | 3240.00
```

<sup>Created on 2023-03-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattansb** [comment]
What was this doing before?

**Comment by strengejacke** [comment]
It was working several months ago, but then Vincent and I came up with a performance improvement by converting model objects to data frames only once (https://github.com/easystats/bayestestR/pull/532). However, in `.describe_posterior()`, instead of model objects, a data frame of posteriors was passed to every function (like `pd()`, `rope()` etc.). This works well in most situations, except when you want to define the rope _range_. This PR fixes this.

**Comment by strengejacke** [comment]
errors seem unrelated

**Pull request merged**
