### PR TITLE
Multivariate rope

### PR DESCRIPTION
**Pull request by bwiernik**
Bug fixes in ROPE for multivariate models

Closes https://github.com/easystats/bayestestR/issues/446

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
do you have a reprex of a multivariate model with which I can try this?

**Comment by bwiernik** [comment]
library(brms)
model <- brm(mvbind(mpg, wt) ~ cyl + disp, data = mtcars)
bayestestR::rope(model)
bayestestR::rope(model, range = list(mpg = c(-.1, .1), wt = c(-.1, .1)))

**Comment by mattansb** [comment]
Looks good (:

**Comment by mattansb** [comment]
I think the printing should split by response? Similar to pd:

```R
pd(model)
#> Probability of Direction mpg
#> 
#> Parameter   | Response |     pd
#> -------------------------------
#> (Intercept) |      mpg |   100%
#> cyl         |      mpg | 54.00%
#> disp        |      mpg | 96.00%
#> 
#> # Fixed effects wt
#> 
#> Parameter   | Response |     pd
#> -------------------------------
#> (Intercept) |       wt |   100%
#> cyl         |       wt | 78.00%
#> disp        |       wt |   100%
```

**Comment by bwiernik** [comment]
Are you familiar with the pd print method? Could you implement that after I merge this?

**Comment by mattansb** [comment]
I am not... I believe @strengejacke is the man for the job.

**Comment by strengejacke** [comment]
I can address the print-issue. _bayestestR_ is not really up to date regarding the new underlying API/functions for `print()`, we should step by step do larger revisions to the print-functions in _bayestestR_.

**Comment by DominiqueMakowski** [comment]
> larger revisions to the print-functions in bayestestR.

and prolly not just print functions 🙈

**Pull request merged**
