### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by mattansb** [comment]
@DominiqueMakowski why did you add back `hypothesis` to `bf_parameters`? (a deprecated argument) Did removing this break any code? (non that I can see)

**Comment by DominiqueMakowski** [comment]
> Did removing this break any code? (non that I can see)

Every documented argument should be in the usage (i.e., in the function definition), so either we remove it altogether, or we keep it for the next release (and remove it after), but deprecate it as it is now

**Comment by mattansb** [comment]
Hmm.. It's been deprecated for the last few releases - I think we can get rid of it altogether, do you agree?

**Comment by DominiqueMakowski** [comment]
oh right I forgot! in that case yes I'll remove it altogether :)

**Comment by strengejacke** [comment]
Please let us do some brainstorming on the name `mhdior` - @DominiqueMakowski especially regarding you, doesn't it sound like Christian Dior to you?

**Comment by strengejacke** [comment]
all checks pass, ready to merge, I'd say.

**Comment by mattansb** [comment]
Oops, forgot I fixed that bug way-back when. Anyway, the new value is the correct one.

**Pull request merged**
