### PR TITLE
dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by mattansb** [comment]
@DominiqueMakowski the Unicode characters are why Travis failed??

**Comment by mattansb** [comment]
HoFv

**Comment by mattansb** [comment]
I... I broke Travis again... What? Why? How??

**Comment by DominiqueMakowski** [comment]
> \* checking S3 generic/method consistency ... WARNING
check_prior:
  function(model, method, simulate_priors, ...)
check_prior.brmsfit:
  function(model, method, effects, component, parameters,
           simulate_priors, ...)

> check_prior:
  function(model, method, simulate_priors, ...)
check_prior.stanreg:
  function(model, method, effects, component, parameters,
           simulate_priors, ...)

image

**Comment by DominiqueMakowski** [comment]
@mattansb @strengejacke what do you think about the slightly updated README https://github.com/easystats/bayestestR/blob/dev/README.md

**Comment by mattansb** [comment]
Look great!

I wonder if / where the `si()` should be added - it's not related to estimating uncertainty in estimation, but rather about quantifying evidence (or uncertainty in evidence?). Maybe as a note with the point-null BF?

**Comment by DominiqueMakowski** [comment]
> I wonder if / where the si() should be added

- We could add it in a new section (just before "Utilities"), something like "Other Bayesian Tricks" (just made me think of Watto saying 'your Bayesian tricks don't work on me')
- Add it also in the Expert tutorial, in a section like 'Beyond significance' 
- We can ship this part as a blogpost!

**Comment by mattansb** [comment]
Love that image!

If you feel like adding it to the README / tutorial, go a head - if you'd rather I do it, might get to it a some point, but I'm in no rush to have this feature... featured ^_^ (a blog post is a good idea though)

**Comment by DominiqueMakowski** [comment]
I suppose we can merge this ^^ ?

**Comment by mattansb** [comment]
I keep getting the imports/ requires wrong. Will fix tomorrow..

**Comment by mattansb** [comment]
Still *some* fail on Travis. This is a job for.. not me :/

**Comment by DominiqueMakowski** [comment]
What about submitting this to CRAN in the next few days? 

@strengejacke how are you doing with your flu? I feel a disturbance in the force 😟

**Comment by mattansb** [comment]
> What about submitting this to CRAN in the next few days?

Sounds good me - I've completed everything I had planned (:

Feel better @strengejacke !

**Comment by strengejacke** [comment]
back at work again. now, actually, I'm suffering from back pain. 😠 pinched sciatica nerve.

**Comment by DominiqueMakowski** [comment]
on travis it fails because:

```
── 1. Failure: map_estimate (@test-map_estimate.R#27)  ─────────────────────────
map_estimate(m, effects = "all", component = "all")$Parameter not equal to c(...).
8/14 mismatches
x[4]: "r_persons[1,Intercept]"
y[4]: "r_persons.1.Intercept."
x[5]: "r_persons[2,Intercept]"
y[5]: "r_persons.2.Intercept."
x[6]: "r_persons[3,Intercept]"
y[6]: "r_persons.3.Intercept."
x[7]: "r_persons[4,Intercept]"
y[7]: "r_persons.4.Intercept."
x[11]: "r_persons__zi[1,Intercept]"
y[11]: "r_persons__zi.1.Intercept."
══ testthat results  ═══════════════════════════════════════════════════════════
```
seems related to brms too

**Comment by strengejacke** [comment]
> seems related to brms too

That one's fixed, insight's on CRAN already (need to submit _parameters_ today as well, but that's unrelated to bayestestR issues...)

**Comment by mattansb** [comment]
Seem to have some fails related to the dimensions of `describe_posterior()`...

**Comment by strengejacke** [comment]
yeah, I can fix this later in office...

**Pull request merged**
