### PR TITLE
Enhance bf

### PR DESCRIPTION
**Pull request by strengejacke**

### CODE REVIEW

**Comment by strengejacke** [comment]
print-style is really a thing of personal preferences... I have revised the print-method for BF-models a bit, to make it less look like what the BF-pkg returns. Feel free to revert / modify / ...

**Comment by mattansb** [comment]
@strengejacke I love this! I clearly have no stylistic instinct... feel free to do this for the other BF printing methods!

**Comment by mattansb** [comment]
@strengejacke @DominiqueMakowski I've update the BF function's docs ***and*** the BF vignette. As the vignette is basically a re-write, would appreciate if you could go over it - I'm sure there are things that can be improved.

Okay, back to grading papers! (Yes, I procrastinate with bayestestR...)

**Comment by mattansb** [comment]
(The merge conflict can be fixed later - I looked at it, it's just Github being overwhelmed with all the changes made, was too hard to track...)

**Comment by DominiqueMakowski** [comment]
Maybe we could resolve the conflicts and merge this into dev and review there?

**Comment by mattansb** [comment]
Alright, I'll give it a try

**Comment by mattansb** [comment]
@DominiqueMakowski @strengejacke I've merged with `dev`. We can continue the discussion over at #194

**Pull request merged**
