### PR TITLE
eti()

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
- [ ] own separate class
- [ ] print method
- [ ] enable `method` arg in `ci()`. @strengejacke this I am not sure how to best implement it, keeping in mind that this method argument is expanded in parameters (e.g., `method="wald"`).

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
(It's dinner time for me so if someone wants to take over for adding the print method it's free 😁)

**Comment by strengejacke** [comment]
I'm away from pc this weekend, so I can get back to this on Monday morning easystats time.

**Comment by DominiqueMakowski** [comment]
enjoy your WE we'll take care of it ☺️

**Comment by mattansb** [comment]
Sorry, I'm also away from the computer this weekend...

**Comment by DominiqueMakowski** [comment]
```
Warning messages:
1: In i.p(...) :
  installation of package ‘bayestestR’ had non-zero exit status
2: In i.p(...) : installation of package ‘see’ had non-zero exit status
missing: insight
The command "Rscript -e 'deps <- remotes::dev_package_deps(dependencies = NA);remotes::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
```

Seems that something's wrong with the installation of insight on oldrel, making travis to fail

**Comment by DominiqueMakowski** [comment]
Should work. Will be submitting to JOSS

**Pull request merged**
