### PR TITLE
update

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
I am not usre why tests fail on linux... it seems like its the rstan problem again

**Comment by DominiqueMakowski** [comment]
It seems that there is still an error with rope for brms objects
```
> test_check("bayestestR")
-- 1. Error: brms (@test-brms.R#13)  -----------------------------------------------------------------------------------
subscript out of bounds
1: testthat::expect_is(rope(model), "data.frame") at testthat/test-brms.R:13
2: quasi_label(enquo(object), label)
3: eval_bare(get_expr(quo), get_env(quo))
4: rope(model)
5: rope.brmsfit(model)
6: .select_rows(dat, "Group", "fixed")
7: which(data[[variable]] == value)
```

I am not sure how to fix it tho, @strengejacke any thoughts?

**Comment by strengejacke** [comment]
I have no problems running the tests, have you checked out the latest source?

**Comment by DominiqueMakowski** [comment]
I've updated brms (and pretty much everything?), but still have the exact same error as above, related to this `7: which(data[[variable]] == value)` subscript out of bounds thing. So weird that you don't!
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] brms_2.8.0 Rcpp_1.0.0
```

**Comment by strengejacke** [comment]
I'll check out the latest source and test again...

**Comment by strengejacke** [comment]
```r
== Results =====================================================================
Duration: 104.3 s

OK:       65
Failed:   0
Warnings: 2
Skipped:  0

test-brms.R:9: warning: brms
There were 72 divergent transitions after warmup. Increasing adapt_delta above 0.8 may help. See
http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup

test-brms.R:9: warning: brms
Examine the pairs() plot to diagnose sampling problems
```

**Comment by strengejacke** [comment]
Ok, maybe I should take the dev-branch... ^^

**Comment by strengejacke** [comment]
ok, should be fixed.

**Comment by strengejacke** [comment]
insight is goin to CRAN within the next 1-2 days, so we can try to release bayestestR pretty soon, I think. I'll merge this PR, so we have a "clean" version. Once insight is on CRAN, we can do the testing.

**Pull request merged**
