### PR TITLE
speed up prior draws + multi level factors docs

### PR DESCRIPTION
**Pull request by strengejacke**
# Description

This PR aims at adding this feature...

# Proposed Changes

I changed the `foo` function so that ...

### CODE REVIEW

**Comment by mattansb** [comment]
@DominiqueMakowski Are we waiting to hear from Singmann to merge?

**Comment by mattansb** [comment]
@strengejacke @DominiqueMakowski 
Once this PR is merged I am officially on vacation!
Good luck with the submission, see you mid-October!

Peace out!

**Comment by DominiqueMakowski** [comment]
There's a persisting warning that I have trouble fixing (and even identifying), could you guys give it a look?

**Comment by strengejacke** [comment]
where do you get a warning? Travis checks look OK, local checks (I'm running on _dev_ 😱 ) also ok... 
So... you have 10 seconds to stop me from merging this PR! 😄

**Comment by DominiqueMakowski** [comment]
weird, on my main laptop, I have an error related to BF (had it since a long time; #180) and an error related to the vignettes (appeared via this update), but on another laptop it's all clear. Let's merge this, I think I'll have to reinstall stuff on my main laptop... ^^

**Pull request merged**
