### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by mattansb**
I've update the these articles / examples to include BFs.
Please let me know if you think anything should be made more clear / simple (I've linked to the main BF vignette in all cases), or if the order of things should be changed (I tried to have it work in the main flow of the vignettes).

### CODE REVIEW

**Comment by mattansb** [comment]
Travis fails here - but locally doesn't... adding `skip_on_travis` 😒
```
── 1. Failure: emmGrid bayesfactor_savagedickey (@test-emmGrid.R#15)  ──────────
log(xsdbf$BF) not equal to c(-2.52, 2.02, -0.27).
2/3 mismatches (average diff: 0.536)
[2]  2.83018 -  2.02 == 0.810
[3] -0.00763 - -0.27 == 0.262
```

**Comment by strengejacke** [comment]
For me, locally the test runs fine as well. I have tweaked the test tolerance.

**Comment by DominiqueMakowski** [comment]
It doens't work for me locally :/

```
Quitting from lines 276-286 (bayes_factors.Rmd) 
   Error: processing vignette 'bayes_factors.Rmd' failed with diagnostics:
   no applicable method for 'group_by_' applied to an object of class "list"
   --- failed re-building 'bayes_factors.Rmd'
```

**Comment by mattansb** [comment]
@DominiqueMakowski for be the BF vignette knits fine... Very weird.

I also changed the `emmGrid` testing a bit to try an please Travis (weird that it was working before - nothing was changed there 😒) - I hope this works.

**Comment by mattansb** [comment]
No idea why this is failing... It seems that all tests pass, and something else is causing failure?

**Comment by DominiqueMakowski** [comment]
I'll take a look (sorry guys this week might be a bit busy for me)

**Comment by DominiqueMakowski** [comment]
What about we try to keep whatever config that passes upon merging in master (so that master is "green", otherwise it's kind of bad advertisement when you see "broken" or "error" on a repo), but we open devel testing throughout the dev cycle on dev so that we have an idea of how it does?

**Comment by strengejacke** [comment]
> otherwise it's kind of bad advertisement

Yes it's a bit annoying, but it's no fault from our side.

**Comment by DominiqueMakowski** [comment]
I'll merge this soon  (tomorrow or such), after I checked the changes ☺️

**Comment by strengejacke** [comment]
> I'll merge this soon (tomorrow or such), after I checked the changes

Ups, sorry! Just read this after merging... :-/

**Comment by strengejacke** [comment]
But note that I have also checked the changes several times, and did not find anything suspicious! :-)

**Comment by DominiqueMakowski** [comment]
@strengejacke I don't know, my flat priors do not exclude the possibility that you are a double agent paid by the Bayes factor side to take over the whole R community... 🙊

**Comment by strengejacke** [comment]
Still, building the pkg source or checking fails on my machine (Windows, R. 3.6), the vignettes still fail to build. Any chance to fix this in time? Afaik, we have 6 days left for re-submission.

**Comment by DominiqueMakowski** [comment]
I'll start looking into it.

**Comment by mattansb** [comment]
@DominiqueMakowski if you get a chance, you're welcome to review the updates I made to the the vignettes (where this PR started 😅)

**Comment by DominiqueMakowski** [comment]
That was on my TODO list

**Comment by DominiqueMakowski** [comment]
And you guys please do also check the paper in the paper folder. It is a mix between the get started vignette and the README. Please copy any changes yo make to the paper over to its original location so that everything is aligned and up-to-date :)

**Pull request merged**
