### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by strengejacke** [comment]
@DominiqueMakowski News-alert!

**Comment by strengejacke** [comment]
(just a reminder: https://github.com/easystats/bayestestR/issues/315#issuecomment-637300318)

**Comment by DominiqueMakowski** [comment]
@mattansb nah but these changes were on purpose 😅 otherwise it fails on my machine

**Comment by DominiqueMakowski** [comment]
Especially if you remove the `[,]` otherwise it removes the "col" names and then emmeans fails

**Comment by DominiqueMakowski** [comment]
and also it's not recommended to directly modify shipped datasets, butter to attach them explicitly

**Comment by mattansb** [comment]
That's so weird! It works fine on my computer 🤷‍♂️🤷‍♂️🤷‍♂️

**Comment by DominiqueMakowski** [comment]
``` r
library(rstanarm)
library(emmeans)
library(ggplot2)

df <- iris
contrasts(df$Species) <- contr.sum

fit_sum <- stan_glm(Sepal.Length ~ Species, data = df,
                    prior = normal(0, c(1, 1), autoscale = FALSE),
                    prior_PD = TRUE, # sample priors
                    family = gaussian(),
                    refresh = 0)

pairs_sum <- pairs(emmeans(fit_sum, ~ Species))
#> Error in as.matrix(object$stanfit)[, nms, drop = FALSE]: subscript out of bounds

em_pairs_samples <- as.data.frame(as.matrix(emmeans::as.mcmc.emmGrid(pairs_sum, names = FALSE)))
#> Error in emmeans::as.mcmc.emmGrid(pairs_sum, names = FALSE): object 'pairs_sum' not found

print(pairs_sum)
#> Error in print(pairs_sum): object 'pairs_sum' not found

ggplot(stack(em_pairs_samples), aes(x = values, fill = ind)) + 
  geom_density(size = 1) + 
  facet_grid(ind ~ .) + 
  labs(x = "prior difference values") + 
  theme(legend.position = "none")
#> Error in stack(em_pairs_samples): object 'em_pairs_samples' not found
```

<sup>Created on 2020-06-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
``` r
df <- iris
contrasts(df$Species)
#>            versicolor virginica
#> setosa              0         0
#> versicolor          1         0
#> virginica           0         1
contrasts(df$Species) <- contr.sum
contrasts(df$Species) 
#>            [,1] [,2]
#> setosa        1    0
#> versicolor    0    1
#> virginica    -1   -1
```

<sup>Created on 2020-06-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
Although now it passes tests  🙉 is it just on my computer that emmeans fail if the contrast thingy has no names? @strengejacke does this work:
```r
library(rstanarm)
library(emmeans)

df <- iris
contrasts(df$Species) <- contr.sum

fit_sum <- stan_glm(Sepal.Length ~ Species, data = df,
                    prior = normal(0, c(1, 1), autoscale = FALSE),
                    prior_PD = TRUE, # sample priors
                    family = gaussian(),
                    refresh = 0)

pairs_sum <- pairs(emmeans(fit_sum, ~ Species))
```

**Comment by strengejacke** [comment]
``` r
library(rstanarm)
#> Loading required package: Rcpp
#> rstanarm (Version 2.19.3, packaged: 2020-02-11 05:16:41 UTC)
#> - Do not expect the default priors to remain the same in future rstanarm versions.
#> Thus, R scripts should specify priors explicitly, even if they are just the defaults.
#> - For execution on a local, multicore CPU with excess RAM we recommend calling
#> options(mc.cores = parallel::detectCores())
#> - bayesplot theme set to bayesplot::theme_default()
#>    * Does _not_ affect other ggplot2 plots
#>    * See ?bayesplot_theme_set for details on theme setting
library(emmeans)

df <- iris
contrasts(df$Species) <- contr.sum

fit_sum <- stan_glm(Sepal.Length ~ Species, data = df,
                    prior = normal(0, c(1, 1), autoscale = FALSE),
                    prior_PD = TRUE, # sample priors
                    family = gaussian(),
                    refresh = 0)

pairs_sum <- pairs(emmeans(fit_sum, ~ Species))
pairs_sum
#>  contrast               estimate lower.HPD upper.HPD
#>  setosa - versicolor     -0.0248     -2.66      2.84
#>  setosa - virginica       0.0579     -4.29      4.63
#>  versicolor - virginica   0.0885     -4.45      4.50
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95

sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.1 (2020-06-06)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  German_Germany.1252         
#>  ctype    German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2020-06-15                  
#> 
#> - Packages -------------------------------------------------------------------
#>  ! package      * version  date       lib source        
#>    assertthat     0.2.1    2019-03-21 [1] CRAN (R 4.0.0)
#>    base64enc      0.1-3    2015-07-28 [1] CRAN (R 4.0.0)
#>    bayesplot      1.7.2    2020-05-28 [1] CRAN (R 4.0.0)
#>    boot           1.3-25   2020-04-26 [2] CRAN (R 4.0.1)
#>    callr          3.4.3    2020-03-28 [1] CRAN (R 4.0.0)
#>    cli            2.0.2    2020-02-28 [1] CRAN (R 4.0.0)
#>    coda           0.19-3   2019-07-05 [1] CRAN (R 4.0.0)
#>    codetools      0.2-16   2018-12-24 [2] CRAN (R 4.0.1)
#>    colorspace     1.4-1    2019-03-18 [1] CRAN (R 4.0.0)
#>    colourpicker   1.0      2017-09-27 [1] CRAN (R 4.0.0)
#>    crayon         1.3.4    2017-09-16 [1] CRAN (R 4.0.0)
#>    crosstalk      1.1.0.1  2020-03-13 [1] CRAN (R 4.0.0)
#>    digest         0.6.25   2020-02-23 [1] CRAN (R 4.0.0)
#>    dplyr          1.0.0    2020-05-29 [1] CRAN (R 4.0.0)
#>    DT             0.13     2020-03-23 [1] CRAN (R 4.0.0)
#>    dygraphs       1.1.1.6  2018-07-11 [1] CRAN (R 4.0.0)
#>    ellipsis       0.3.1    2020-05-15 [1] CRAN (R 4.0.0)
#>    emmeans      * 1.4.7    2020-05-25 [1] CRAN (R 4.0.0)
#>    estimability   1.3      2018-02-11 [1] CRAN (R 4.0.0)
#>    evaluate       0.14     2019-05-28 [1] CRAN (R 4.0.0)
#>    fansi          0.4.1    2020-01-08 [1] CRAN (R 4.0.0)
#>    fastmap        1.0.1    2019-10-08 [1] CRAN (R 4.0.0)
#>    generics       0.0.2    2018-11-29 [1] CRAN (R 4.0.0)
#>    ggplot2        3.3.1    2020-05-28 [1] CRAN (R 4.0.0)
#>    ggridges       0.5.2    2020-01-12 [1] CRAN (R 4.0.0)
#>    glue           1.4.1    2020-05-13 [1] CRAN (R 4.0.0)
#>    gridExtra      2.3      2017-09-09 [1] CRAN (R 4.0.0)
#>    gtable         0.3.0    2019-03-25 [1] CRAN (R 4.0.0)
#>    gtools         3.8.2    2020-03-31 [1] CRAN (R 4.0.0)
#>    highr          0.8      2019-03-20 [1] CRAN (R 4.0.0)
#>    htmltools      0.4.0    2019-10-04 [1] CRAN (R 4.0.0)
#>    htmlwidgets    1.5.1    2019-10-08 [1] CRAN (R 4.0.0)
#>    httpuv         1.5.4    2020-06-06 [1] CRAN (R 4.0.0)
#>    igraph         1.2.5    2020-03-19 [1] CRAN (R 4.0.0)
#>    inline         0.3.15   2018-05-18 [1] CRAN (R 4.0.0)
#>    knitr          1.28     2020-02-06 [1] CRAN (R 4.0.0)
#>    later          1.1.0.1  2020-06-05 [1] CRAN (R 4.0.0)
#>    lattice        0.20-41  2020-04-02 [2] CRAN (R 4.0.1)
#>    lifecycle      0.2.0    2020-03-06 [1] CRAN (R 4.0.0)
#>    lme4           1.1-23   2020-04-07 [1] CRAN (R 4.0.0)
#>    loo            2.2.0    2019-12-19 [1] CRAN (R 4.0.0)
#>    magrittr       1.5      2014-11-22 [1] CRAN (R 4.0.0)
#>    markdown       1.1      2019-08-07 [1] CRAN (R 4.0.0)
#>    MASS           7.3-51.6 2020-04-26 [2] CRAN (R 4.0.1)
#>    Matrix         1.2-18   2019-11-27 [2] CRAN (R 4.0.1)
#>    matrixStats    0.56.0   2020-03-13 [1] CRAN (R 4.0.0)
#>    mime           0.9      2020-02-04 [1] CRAN (R 4.0.0)
#>    miniUI         0.1.1.1  2018-05-18 [1] CRAN (R 4.0.0)
#>    minqa          1.2.4    2014-10-09 [1] CRAN (R 4.0.0)
#>    multcomp       1.4-13   2020-04-08 [1] CRAN (R 4.0.0)
#>    munsell        0.5.0    2018-06-12 [1] CRAN (R 4.0.0)
#>    mvtnorm        1.1-1    2020-06-09 [1] CRAN (R 4.0.0)
#>    nlme           3.1-148  2020-05-24 [2] CRAN (R 4.0.1)
#>    nloptr         1.2.2.1  2020-03-11 [1] CRAN (R 4.0.0)
#>    pillar         1.4.4    2020-05-05 [1] CRAN (R 4.0.0)
#>    pkgbuild       1.0.8    2020-05-07 [1] CRAN (R 4.0.0)
#>    pkgconfig      2.0.3    2019-09-22 [1] CRAN (R 4.0.0)
#>    plyr           1.8.6    2020-03-03 [1] CRAN (R 4.0.0)
#>    prettyunits    1.1.1    2020-01-24 [1] CRAN (R 4.0.0)
#>    processx       3.4.2    2020-02-09 [1] CRAN (R 4.0.0)
#>    promises       1.1.1    2020-06-09 [1] CRAN (R 4.0.0)
#>    ps             1.3.3    2020-05-08 [1] CRAN (R 4.0.0)
#>    purrr          0.3.4    2020-04-17 [1] CRAN (R 4.0.0)
#>    R6             2.4.1    2019-11-12 [1] CRAN (R 4.0.0)
#>    Rcpp         * 1.0.4.6  2020-04-09 [1] CRAN (R 4.0.0)
#>  D RcppParallel   5.0.1    2020-05-06 [1] CRAN (R 4.0.0)
#>    reshape2       1.4.4    2020-04-09 [1] CRAN (R 4.0.0)
#>    rlang          0.4.6    2020-05-02 [1] CRAN (R 4.0.0)
#>    rmarkdown      2.2      2020-05-31 [1] CRAN (R 4.0.0)
#>    rsconnect      0.8.16   2019-12-13 [1] CRAN (R 4.0.0)
#>    rstan          2.19.3   2020-02-11 [1] CRAN (R 4.0.0)
#>    rstanarm     * 2.19.3   2020-02-11 [1] CRAN (R 4.0.0)
#>    rstantools     2.1.0    2020-06-01 [1] CRAN (R 4.0.0)
#>    sandwich       2.5-1    2019-04-06 [1] CRAN (R 4.0.0)
#>    scales         1.1.1    2020-05-11 [1] CRAN (R 4.0.0)
#>    sessioninfo    1.1.1    2018-11-05 [1] CRAN (R 4.0.0)
#>    shiny          1.4.0.2  2020-03-13 [1] CRAN (R 4.0.0)
#>    shinyjs        1.1      2020-01-13 [1] CRAN (R 4.0.0)
#>    shinystan      2.5.0    2018-05-01 [1] CRAN (R 4.0.0)
#>    shinythemes    1.1.2    2018-11-06 [1] CRAN (R 4.0.0)
#>    StanHeaders    2.21.0-5 2020-06-09 [1] CRAN (R 4.0.0)
#>    statmod        1.4.34   2020-02-17 [1] CRAN (R 4.0.0)
#>    stringi        1.4.6    2020-02-17 [1] CRAN (R 4.0.0)
#>    stringr        1.4.0    2019-02-10 [1] CRAN (R 4.0.0)
#>    survival       3.1-12   2020-04-10 [2] CRAN (R 4.0.1)
#>    TH.data        1.0-10   2019-01-21 [1] CRAN (R 4.0.0)
#>    threejs        0.3.3    2020-01-21 [1] CRAN (R 4.0.0)
#>    tibble         3.0.1    2020-04-20 [1] CRAN (R 4.0.0)
#>    tidyselect     1.1.0    2020-05-11 [1] CRAN (R 4.0.0)
#>    vctrs          0.3.1    2020-06-05 [1] CRAN (R 4.0.0)
#>    withr          2.2.0    2020-04-20 [1] CRAN (R 4.0.0)
#>    xfun           0.14     2020-05-20 [1] CRAN (R 4.0.0)
#>    xtable         1.8-4    2019-04-21 [1] CRAN (R 4.0.0)
#>    xts            0.12-0   2020-01-19 [1] CRAN (R 4.0.0)
#>    yaml           2.2.1    2020-02-01 [1] CRAN (R 4.0.0)
#>    zoo            1.8-8    2020-05-02 [1] CRAN (R 4.0.0)
#> 
#> [1] C:/Users/mail/Documents/R/win-library/4.0
#> [2] C:/Program Files/R/R-4.0.1/library
#> 
#>  D -- DLL MD5 mismatch, broken installation.
```

<sup>Created on 2020-06-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Not that you'll most likely into check failures due to "non-anchored" links, i.e. all `\link{}` tags to _external_ package functions (i.e. functions in other packages) won't work with the current roygen-version due to changes in the R check system. See [this discussion](https://stat.ethz.ch/pipermail/r-package-devel/2020q2/005563.html) (and follow up threads) for details.

**Comment by strengejacke** [comment]
Do you plan to address https://github.com/easystats/insight/issues/199 before submission?

**Comment by DominiqueMakowski** [comment]
> Do you plan to address easystats/insight#199 before submission?

Should we leave that for next release when insight's support is on CRAN?

**Comment by strengejacke** [comment]
> > Do you plan to address [easystats/insight#199](https://github.com/easystats/insight/issues/199) before submission?
> 
> Should we leave that for next release when insight's support is on CRAN?

Haha, true. I thought it was already in the recent CRAN version.

**Comment by DominiqueMakowski** [comment]
> Not that you'll most likely into check failures due to "non-anchored" links,

Will winbuilder checks detect it?

**Comment by strengejacke** [comment]
Not sure, I think these mainly occur on Linux (of course...)

**Comment by DominiqueMakowski** [comment]
package bayestestR_0.7.0.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/bayestestR_0.7.0_20200616_020810/Windows/00check.log>
Status: 1 NOTE
Debian: <https://win-builder.r-project.org/incoming_pretest/bayestestR_0.7.0_20200616_020810/Debian/00check.log>
Status: 1 WARNING

@strengejacke what do you see? 👀

**Comment by strengejacke** [comment]
ehm... the websites are "empty"...

**Comment by strengejacke** [comment]
Any text files attached to your mail?

**Comment by DominiqueMakowski** [comment]
nope

**Comment by DominiqueMakowski** [comment]
```

  Found the following (possibly) invalid URLs:
    URL: https://www.cogsci.nl/blog/interpreting-bayesian-repeated-measures-in-jasp
      From: inst/doc/bayes_factors.html
      Status: 404
      Message: Not Found

Flavor: r-devel-linux-x86_64-debian-gcc
Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers
  Maintainer: 'Dominique Makowski <dom.makowski@gmail.com>'

Flavor: r-devel-linux-x86_64-debian-gcc
Check: Rd cross-references, Result: WARNING
  Non-file package-anchored link(s) in documentation object 'estimate_density.Rd':
    '[stats]{bw.nrd}'

  Non-file package-anchored link(s) in documentation object 'p_direction.Rd':
    '[brms]{posterior_average}'

  Non-file package-anchored link(s) in documentation object 'weighted_posteriors.Rd':
    '[brms]{posterior_average}'

```
got it meyabe it's this (was written below)

**Comment by DominiqueMakowski** [comment]
as you called, the non-anchored links 😁

**Comment by strengejacke** [comment]
Since I updated _parameters_ and _performance_ lately, I changed those links to something like `\code{brms::posterior_average()}` or so, avoiding the `\link{}` tag (note that link works for internal functions though).

**Comment by DominiqueMakowski** [comment]
Interesting, the link flagged as broken seems to work: https://www.cogsci.nl/blog/interpreting-bayesian-repeated-measures-in-jasp 🤔

**Comment by strengejacke** [comment]
I think both the R team and the roxygen maintainers are working on solutions, but I'm not sure when this issue will be resolved. So if you're ok to remove links to external functions, you could submit now. If you insist on keeping these links, you need to wait with submission... 

Or, you install from [this PR](https://github.com/r-lib/roxygen2/pull/1109), that should probably work as well.

**Comment by strengejacke** [comment]
> Interesting, the link flagged as broken seems to work: https://www.cogsci.nl/blog/interpreting-bayesian-repeated-measures-in-jasp 🤔

The website doesn't render well, so maybe it was temporarily down during checks? That happens quite a lot.

**Comment by DominiqueMakowski** [comment]
> The website doesn't render well, so maybe it was temporarily down during checks? That happens quite a lot.

Right, so we leave it as is and eventually mark it as false positive?

>  Non-file package-anchored link(s) in documentation object 'estimate_density.Rd':
    '[stats]{bw.nrd}'

The problem is that we don't have this arg... I.e., IMO it comes from `@inheritParams stats::density`... any ideas?

**Comment by strengejacke** [comment]
> > The website doesn't render well, so maybe it was temporarily down during checks? That happens quite a lot.
> 
> Right, so we leave it as is and eventually mark it as false positive?
> 

Yes, or maybe it's even gone for the next submit (you need to re-submit anyway, right?)

> > Non-file package-anchored link(s) in documentation object 'estimate_density.Rd':
> > '[stats]{bw.nrd}'
> 
> The problem is that we don't have this arg... I.e., IMO it comes from `@inheritParams stats::density`... any ideas?

hm... I don't think this gets resolved when using the dev-version of roxygen, as the help-page from `stats::density()` is affected. I guess, we should or need to copy/paste the function arguments and add them as `@param` in `estimate_density.R`.

**Comment by DominiqueMakowski** [comment]
Can't we flag it as false positive as well? The CRAN team might be okay since the issue originates from "within R"

**Comment by strengejacke** [comment]
You can try it... The problem _might_ be that `@inheritParams stats::density` generates following code in the rd-file:

```
\item{bw}{the smoothing bandwidth to be used.  The kernels are scaled
    such that this is the standard deviation of the smoothing kernel.
    (Note this differs from the reference books cited below, and from S-PLUS.)

    \code{bw} can also be a character string giving a rule to choose the
    bandwidth.  See \code{\link[stats]{bw.nrd}}. \cr The default,
    \code{"nrd0"}, has remained the default for historical and
    compatibility reasons, rather than as a general recommendation,
    where e.g., \code{"SJ"} would rather fit, see also Venables and
    Ripley (2002).

    The specified (or computed) value of \code{bw} is multiplied by
    \code{adjust}.
  }
```

CRAN does not care about _how_ we generate the rd-files, but in fact we have an external link here. So actually, it's not an "internal R" problem, but rather our "laziness" to define arguments by ourselves.

**Comment by DominiqueMakowski** [comment]
😓

**Comment by strengejacke** [comment]
> This is how to look up the filename. The first "sp" is the topic name, the second is the package name.

```r
> help("sp", "sp")[[1]]
[1] "C:/Users/csard/R/win-library/4.0/sp/help/00sp"
```

> So you need to link to the "00sp.Rd" file:  \link[sp:00sp]{sp}

**Pull request merged**
