### PR TITLE
Move some args into ...

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
feel free to merge whenever and i'll submit to CRAN afterwards :)

**Comment by mattansb** [comment]
Tests are failing for unrelated reasons.

@DominiqueMakowski you can merge and submit (:

**Comment by strengejacke** [comment]
Remember to bump to a correct version on the description file 😉

**Comment by DominiqueMakowski** [comment]
> Remember to bump to a correct version on the description file

me? You mean when I submit? Wait I feel like I forgot everything, can you write explicitly about what I should make sure of 🙈

**Comment by DominiqueMakowski** [comment]
Can we merge this?

**Pull request merged**
