### PR TITLE
CRAN submission

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
has been submitted

**Comment by DominiqueMakowski** [comment]
thanks, package bayestestR_0.2.5.tar.gz is on its way to CRAN.

received 2 hours ago. that was fast

**Comment by strengejacke** [comment]
So we can merge this?

**Comment by DominiqueMakowski** [comment]
gimme 2 sec I'll merge and make a release

**Pull request merged**
