### PR TITLE
Fix CRAN checks

### PR DESCRIPTION
**Pull request by strengejacke**
related to https://github.com/easystats/bayestestR/issues/282

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
It passed all CRAN checks, I submitted to CRAN

**Comment by DominiqueMakowski** [comment]
```
package bayestestR_0.5.2.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/bayestestR_0.5.2_20200206_024941/Windows/00check.log>
Status: OK
Debian: <https://win-builder.r-project.org/incoming_pretest/bayestestR_0.5.2_20200206_024941/Debian/00check.log>
Status: 1 WARNING, 1 NOTE
```
Debian fails because of rstanarm

```
* checking package dependencies ... NOTE
Package suggested but not available for checking: ‘rstanarm’
```

What should we do? Report a false positive failure? Resubmit later?

**Comment by strengejacke** [comment]
But that's just the note, not the warning. Where do the check yield the warning?

**Comment by strengejacke** [comment]
Ok, these are the lines that error:

This code chunk (362-367) in _example1.rmd_ fail, because when rstanarm is _not_ available, all chunks are _not_ evaluated. In this case, it's not evaluated and we have no value for `twosided_p`.

```{r message=FALSE, warning=FALSE}
pd <- 97.82
onesided_p <- 1 - pd / 100  
twosided_p <- onesided_p * 2
twosided_p
```

Then, the inline-code at line 369 fails, because it requires `twosided_p`, which is not avaiable

> If we ran our model in the frequentist framework, we should approximately observe an effect with a *p*-value of `r round(twosided_p, digits=3)`. **Is that true?**


Solution: You may try to explicitely set `eval=TRUE` just for the above code chunk. Else... no good idea?

**Comment by strengejacke** [comment]
ok, I think there were still some logical operation issues in the setup-chunk of the vignettes. I also forces the evaluation of the above code chunk.

**Pull request merged**
