### PR TITLE
prepare CRAN release

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by strengejacke** [comment]
If you haven't submitted yet, you could change the url in the DESCRIPTION:

https://github.com/easystats/bayestestR -> https://easystats.github.io/bayestestR/

**Comment by strengejacke** [comment]
Just saw: https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/parameters-00check.html

Reason: https://cran.r-project.org/web/packages/projpred/index.html

Not sure if bayestestR might also be affected?

**Comment by DominiqueMakowski** [comment]
It seems like the new insight still didn't make it on their checks server, I'll trigger the checks again this evening or tomorrow, other than that it pretty much passes

**Comment by strengejacke** [comment]
You can see here for which platforms the package has been built:
https://cran.r-project.org/web/checks/check_results_insight.html
But this should not affect CRAN submission...I could submit parameters shortly after insight, though parameters required the new insight version.

**Comment by DominiqueMakowski** [comment]
```
Dear maintainer,

thanks, package bayestestR_0.5.0.tar.gz is on its way to CRAN.

Best regards,
CRAN teams' auto-check service
Package check result: OK

No changes to worse in reverse depends.
```

**Pull request merged**
