### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Started changing the default CI level, but I'll need your eyes to go through the documentation and vignettes to double_check and make sure everything is order :)

**Comment by DominiqueMakowski** [comment]
@mattansb it seems that something has been modified in BFsd that breaks the test of `describe_posterior`: it doesn't merge right when a simple vector is passed

**Comment by mattansb** [comment]
Should work now.

**Comment by strengejacke** [comment]
ok, I merge and will also check the 89er-stuff.

**Pull request merged**
