### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
submitted

**Comment by strengejacke** [comment]
Have you addressed this issue: https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/bayestestR-00check.html?

**Comment by DominiqueMakowski** [comment]
`on its way to CRAN`

> Have you addressed this issue: https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/bayestestR-00check.html?

Mmh not specifically but it didn't show in the checks, it says everything OK

**Comment by strengejacke** [comment]
maybe it was temporary, and checks have not been re-initiated on that system again...

**Comment by strengejacke** [comment]
Good to see you caring so much about news files... 

> bayestestR 0.5.x

:-D

**Comment by DominiqueMakowski** [comment]
🙉 it's on my roadmap

**Pull request merged**
