### PR TITLE
minor rewrite of bayes factor vignette

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Although nobody asked for this, I have made some minor changes (mostly phrasing and emphasis related) to the vignette for Bayes Factors.

### CODE REVIEW

**Comment by mattansb** [comment]
You touched my baby!!! How dare you!!!

I'll give this a look tomorrow (:

**Comment by mattansb** [comment]
@IndrajeetPatil It is really hard to track what are just new line breaks and what actual changes :(

I made some fixes, hope I didn't miss anything (:

**Comment by IndrajeetPatil** [comment]
Sorry, my bad. 😥 

I should have done the 80-character styling first and _then_ did the rewrite.  Will do that for other vignettes if I work on them.

Your edits look good to me. I will merge once the checks are completed.

**Comment by IndrajeetPatil** [comment]
Do you think the highlighted part of the sentence here needs a bit more context? I think it feels like a bit of a jump for a newcomer.

Screenshot 2021-03-07 at 12 47 57

**Comment by mattansb** [comment]
Maybe "Under these priors, the odds of the drug's effect being outside the range of [*] compared to it being inside this range is 2.2."

\* I don't remember lol

**Pull request merged**
