### PR TITLE
Prepare CRAN submission

### PR DESCRIPTION
**Pull request by strengejacke**

### CODE REVIEW

**Comment by strengejacke** [comment]
Hey @DominiqueMakowski, still active on GitHub? 😎 
Once _datawizard_ is accepted on CRAN, we need to submit _bayestestR_ next, as a prerequisite for _parameters_ (which has a deadline until 25th Oct).
All checks here pass, maybe we submit to win-builder (need _datawizard_ to be built on windows), and then use this PR for CRAN submission (at some time next week).

**Comment by DominiqueMakowski** [comment]
https://win-builder.r-project.org/m3V5vs6T5uKJ/00check.log

**Comment by strengejacke** [comment]
Checks on old-rel look good. Maybe we wait until _datawizard 0.13.0_ is available for win-devel, check on that version with win-builder, and then submit?

**Comment by strengejacke** [comment]
Were checks on R-release also ok? R-devel still not available for _datawizard_ win-builder...

**Comment by DominiqueMakowski** [comment]
https://win-builder.r-project.org/jYzTaqARsGOu/

**Comment by strengejacke** [comment]
ok, thanks. So we either wait for devel-version of _datawizard_ to be built, or you just submit _bayestestR_, using this PR (and we don't test on win-builder R-devel). I _think_ it's not necessary, because everything should be fine. What do you think?

**Comment by DominiqueMakowski** [comment]
https://win-builder.r-project.org/incoming_pretest/bayestestR_0.15.0_20241009_134338/Windows/00check.log 👀

**Comment by strengejacke** [comment]
> bayesfactor 10.14   0.94   11.13

This is annoying, sometimes, these example run under 10 secs, sometimes take much longer, and we didn't change anything... :-/
Let me fix that example.

**Comment by strengejacke** [comment]
ok, I just put parts of the examples into `dontrun{}`, if that's ok for you.

**Comment by strengejacke** [comment]
Have you re-submitted already?

**Comment by strengejacke** [comment]
Any updates on the state of submission?

**Comment by DominiqueMakowski** [comment]
Came back with the same NOTE 

* checking examples ... [36s] NOTE
Examples with CPU (user + system) or elapsed time > 10s
             user system elapsed
bayesfactor 10.47   0.84   11.35

**Comment by strengejacke** [comment]
Hm, I thought replacing donttest with dontrun is sufficient?

**Comment by strengejacke** [comment]
Have you pulled the latest commits from this PR? There's only this example left running:

```r
library(bayestestR)

prior <- distribution_normal(1000, mean = 0, sd = 1)
posterior <- distribution_normal(1000, mean = 0.5, sd = 0.3)

bayesfactor(posterior, prior = prior, verbose = FALSE)
```

which takes some milliseconds. All remaining examples are now `## Not run:`.

**Comment by strengejacke** [comment]
Ok, let's put *everything* in `dontrun()`, then there can't be any time left for computation. Can you pull the latest commit and try to re-submit? Very strange...

**Comment by DominiqueMakowski** [comment]
https://win-builder.r-project.org/incoming_pretest/bayestestR_0.15.0_20241015_120908/Windows/00check.log same note, could you try submittting yourself and I'll validate?

**Comment by strengejacke** [comment]
That's pretty strange... I can try submitting.

**Comment by strengejacke** [comment]
ok, submitted. You just need to confirm the submission. If this still doesn't pass, we should write the CRAN team.

**Comment by DominiqueMakowski** [comment]
submitted

**Comment by strengejacke** [comment]
🤞

**Comment by strengejacke** [comment]
Ok, seems like initial checks have passed and there's something else we need to respond to?

**Pull request merged**
