### PR TITLE
add support for blavaan

### PR DESCRIPTION
**Pull request by mattansb**
- Posterior Description
  - [x] describe_posterior - waiting for https://github.com/easystats/insight/issues/320
  - [x] describe_prior
  - [x] sexit
- Centrality and Uncertainty
  - [x] point_estimate
  - [x] map_estimate
  - [x] eti
  - [x] hdi
  - [x] ci - conflicts with `parameters`
- Effect Existence and Significance
  - Posterior Based Methods
    - [x] mhdior
    - [x] p_direction
    - [x] p_rope
    - [x] p_map
    - [x] p_sig
    - [x] rope
    - [ ] ~rope_range~
    - [x] equivalence_test
  - Bayes factors
    - [x] bayesfactor_parameters
    - [x] bayesfactor_models
    - [ ] ~bayesfactor_inclusion~
    - [x] bayesfactor_restricted
    - [x] si
    - [x] weighted_posteriors
- Model Diagnostics
  - [x] diagnostic_posterior
  - [ ] sensitivity_to_prior - @DominiqueMakowski might want to do this as some other time...
  - [x] check_prior
  - [x] simulate_prior
  - [x] unupdate
  - [x] effective_sample
  - [x] mcse
- Density Estimation
  - [x] estimate_density

Other:
- [x] printing is weird
- [x] tests

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
can we merge that too?

**Comment by mattansb** [comment]
Nope. Still a lot missing.

This is WIP

**Comment by mattansb** [comment]
Okay, this is essentially done!

Three issues:

1. Waiting for https://github.com/easystats/insight/issues/320
2. `sensitivity_to_prior()` - @DominiqueMakowski I didn't implement it, because the way priors are specified here are different than brms/rstanarm. Should I open a low priorety issue for someone (you!) to address later?
2. There is a `ci.blavaan` method in `parameters` - @strengejacke What do you want to do?

**Comment by DominiqueMakowski** [comment]
> Should I open a low priorety issue for someone (you!) to address later?

Yeah! shouldn't insight::get_priors return a consistent output tho?

**Comment by mattansb** [comment]
It does, the problem is with updating the model to use "new" priors.

**Comment by strengejacke** [comment]
> There is a ci.blavaan method in parameters - @strengejacke What do you want to do?

I don't mind, but I think it would be better located in bayestestR then. Just need to slightly revise blavaan-support in _parameters_ then.

**Comment by mattansb** [comment]
Alright, merging (all the errors seem unrelated to any of the changes I've made).

**Pull request merged**
